name: plant-health-ai
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - matplotlib
  - scikit-learn
  - numpy
  - pillow
  - pip
  - pip:
      - kaggle
      - tqdm
      - streamlit
      - fastapi
      - uvicorn
